### ISSUE TITLE
short password not blocking going to captcha

### ISSUE THREAD

**Issue by smithb1994** [CyberAllianceLLC/pullgrid_client#12]
short password not blocking going to captcha with upload video or new playlist.

**Comment by smithp1992** [comment]
I'm thinking a minimum length of 5 characters for the passwords.

**Comment by smithb1994** [comment]
it goes to captcha without checking character count.

**Comment by smithp1992** [comment]
Adding the minlength of 5 to the inputs of new playlist, video, and comments.
